version: '3.8'

services:
  portfolio_app:
    build: . 
    container_name: portfolio_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - prometheus 

  # 2. Node Exporter (Monitors the host) - REMOVED host network mode
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    # Removed: network_mode: host
    # Removed: command: ['--path.rootfs=/host']
    # Removed: volumes: ['/:/host:ro,rslave']
    
    # We will simply monitor the Node Exporter container itself (CPU/Mem of container, which is fine for basic T3 monitoring)
    # The container will now be on the default Docker network
    restart: always
    ports:
      - "9100:9100" # Expose the port so Prometheus (ID 1860) can access the metrics
    
  # 3. Prometheus Monitoring Server (UNCHANGED)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # 4. Grafana Visualization Dashboard (UNCHANGED)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=YourSecurePassword123 
    depends_on:
      - prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}