version: '3.8'

services:
  # 1. Your React Portfolio Application
  portfolio_app:
    build: . 
    container_name: portfolio_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - prometheus
      - blackbox_exporter 

  # 2. Node Exporter (System Monitoring)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100" 
      
  # 3. Blackbox Exporter (HTTP/Health Check Tool) - The fix for portfolio_app status
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: always
    ports:
      - "9115:9115"

  # 4. Prometheus Monitoring Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      # Mounts the configuration defined in the configs: section below
      - type: config
        source: prometheus_config 
        target: /etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node_exporter
      - blackbox_exporter

  # 5. Grafana Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=YourSecurePassword123 
    depends_on:
      - prometheus

# Define Volumes for Data Persistence
volumes:
  prometheus_data:
  grafana_data:
  
# Define Configuration for Prometheus (FINAL, CORRECT CONFIGURATION)
configs:
  prometheus_config:
    name: prometheus_config
    content: |
      global:
        scrape_interval: 15s 
      scrape_configs:
        # 1. Scrape Prometheus itself
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        # 2. Scrape the Node Exporter 
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['node_exporter:9100']
            
        # 3. Portfolio Site Health Check (Uses Blackbox for HTTP 200 check)
        - job_name: 'portfolio_health_check'
          metrics_path: /probe
          params:
            module: [http_2xx] 
          static_configs:
            - targets: ['http://portfolio_app:80/'] 
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              regex: '(.*)'
              target_label: instance
            - target_label: __address__
              replacement: 'blackbox_exporter:9115'