version: '3.8'

services:
  # 1. Your React Portfolio Application
  portfolio_app:
    build: . 
    container_name: portfolio_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - prometheus
      - blackbox_exporter 

  # 2. Node Exporter (System Monitoring)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100" 
      
  # 3. Blackbox Exporter (HTTP/Health Check Tool)
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: always
    ports:
      - "9115:9115"

  # 4. Prometheus Monitoring Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      # FIX: Use simple bind mount (type: bind is the default, so we just specify the path)
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node_exporter
      - blackbox_exporter

  # 5. Grafana Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=YourSecurePassword123 
    depends_on:
      - prometheus

# Define Volumes for Data Persistence
volumes:
  prometheus_data: {}
  grafana_data: {}