global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Scrape the Node Exporter (Now on Docker Network)
  - job_name: 'node_exporter_aws_t3'
    # FIX: Revert to Docker service name since we removed 'network_mode: host'
    static_configs:
      - targets: ['node_exporter:9100']
      
  # 3. Scrape the portfolio application (HTTP Health Check)
  - job_name: 'portfolio_site_health'
    metrics_path: / 
    static_configs:
      - targets: ['portfolio_app:80']
    # FIX: Relabeling rule to allow Prometheus to consider the scrape successful 
    # even if the Content-Type is text/html (your React page).
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        replacement: 'true'
        target_label: scrape_success