global:
  scrape_interval: 15s 

scrape_configs:
  # 1. Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Scrape the Node Exporter 
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
      
  # 3. Portfolio Site Health Check (Uses Blackbox Exporter)
  - job_name: 'portfolio_health_check'
    metrics_path: /probe
    params:
      module: [http_2xx] # Checks for a 200 OK status, fixing the Content-Type error
    static_configs:
      - targets: ['http://portfolio_app:80/'] 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        regex: '(.*)'
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'